// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGeneration = "generation"

// Generation mapped from table <generation>
type Generation struct {
	VideoGameTitles StringSlice `gorm:"column:video_game_titles;type:jsonb;comment:the video game titles that relates with the generation" json:"video_game_titles"` // the video game titles that relates with the generation
	Generation      int64       `gorm:"column:generation;type:bigint;primaryKey;comment:generation number" json:"generation"`                                        // generation number
}

// TableName Generation's table name
func (*Generation) TableName() string {
	return TableNameGeneration
}
