// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePokemon = "pokemon"

// Pokemon mapped from table <pokemon>
type Pokemon struct {
	Name           string `gorm:"column:name;type:character varying(255);not null;comment:the name of the pokemon" json:"name"`                     // the name of the pokemon
	Form           string `gorm:"column:form;type:character varying(255);not null;comment:the form of the pokemon" json:"form"`                     // the form of the pokemon
	ID             int64  `gorm:"column:id;type:bigint;primaryKey;default:nextval('public.pokemon_id_seq;comment:pk id for each pokemon" json:"id"` // pk id for each pokemon
	Generation     int64  `gorm:"column:generation;type:bigint;not null;default:1;comment:the pokemon's generation" json:"generation"`              // the pokemon's generation
	Speed          int64  `gorm:"column:speed;type:bigint;not null;comment:pokemon speed" json:"speed"`                                             // pokemon speed
	SpecialDefense int64  `gorm:"column:special_defense;type:bigint;not null;comment:pokemon special defense" json:"special_defense"`               // pokemon special defense
	SpecialAttack  int64  `gorm:"column:special_attack;type:bigint;not null;comment:pokemon special attack" json:"special_attack"`                  // pokemon special attack
	Defense        int64  `gorm:"column:defense;type:bigint;not null;comment:pokemon defense" json:"defense"`                                       // pokemon defense
	Attack         int64  `gorm:"column:attack;type:bigint;not null;comment:pokemon attack" json:"attack"`                                          // pokemon attack
	Hp             int64  `gorm:"column:hp;type:bigint;not null;comment:pokemon hit point" json:"hp"`                                               // pokemon hit point
	Total          int64  `gorm:"column:total;type:bigint;not null;comment:total stats" json:"total"`                                               // total stats
	Type2          int64  `gorm:"column:type_2;type:bigint;not null;default:(-1);comment:the second type of the pokemon" json:"-"`                  // the second type of the pokemon
	Type1          int64  `gorm:"column:type_1;type:bigint;not null;default:(-1);comment:the first type of the pokemon" json:"-"`                   // the first type of the pokemon
	PokedexNumber  int64  `gorm:"column:pokedex_number;type:bigint;not null;comment:pokemon pokedex number (national no)" json:"pokedex_number"`    // pokemon pokedex number (national no)
	Type1String    string `gorm:"-" json:"type_1" comment:"This is the string of type_1 from db"`
	Type2String    string `gorm:"-" json:"type_2" comment:"This is the string of type_2 from db"`
}

// TableName Pokemon's table name
func (*Pokemon) TableName() string {
	return TableNamePokemon
}
