// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePokemonType = "pokemon_type"

// PokemonType mapped from table <pokemon_type>
type PokemonType struct {
	Name string `gorm:"column:name;type:character varying(255);not null;comment:name of the type" json:"name"`                                  // name of the type
	ID   int64  `gorm:"column:id;type:bigint;primaryKey;default:nextval('public.pokemon_types_id_seq;comment:pk id of pokemon types" json:"id"` // pk id of pokemon types
}

// TableName PokemonType's table name
func (*PokemonType) TableName() string {
	return TableNamePokemonType
}
