// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	Generation  *generation
	Pokemon     *pokemon
	PokemonType *pokemonType
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Generation = &Q.Generation
	Pokemon = &Q.Pokemon
	PokemonType = &Q.PokemonType
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		Generation:  newGeneration(db, opts...),
		Pokemon:     newPokemon(db, opts...),
		PokemonType: newPokemonType(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Generation  generation
	Pokemon     pokemon
	PokemonType pokemonType
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Generation:  q.Generation.clone(db),
		Pokemon:     q.Pokemon.clone(db),
		PokemonType: q.PokemonType.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Generation:  q.Generation.replaceDB(db),
		Pokemon:     q.Pokemon.replaceDB(db),
		PokemonType: q.PokemonType.replaceDB(db),
	}
}

type queryCtx struct {
	Generation  *generationDo
	Pokemon     *pokemonDo
	PokemonType *pokemonTypeDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Generation:  q.Generation.WithContext(ctx),
		Pokemon:     q.Pokemon.WithContext(ctx),
		PokemonType: q.PokemonType.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
