// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"pokemon-api-server/internal/model"
)

func newGeneration(db *gorm.DB, opts ...gen.DOOption) generation {
	_generation := generation{}

	_generation.generationDo.UseDB(db, opts...)
	_generation.generationDo.UseModel(&model.Generation{})

	tableName := _generation.generationDo.TableName()
	_generation.ALL = field.NewAsterisk(tableName)
	_generation.VideoGameTitles = field.NewField(tableName, "video_game_titles")
	_generation.Generation = field.NewInt64(tableName, "generation")

	_generation.fillFieldMap()

	return _generation
}

type generation struct {
	generationDo

	ALL             field.Asterisk
	VideoGameTitles field.Field // the video game titles that relates with the generation
	Generation      field.Int64 // generation number

	fieldMap map[string]field.Expr
}

func (g generation) Table(newTableName string) *generation {
	g.generationDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g generation) As(alias string) *generation {
	g.generationDo.DO = *(g.generationDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *generation) updateTableName(table string) *generation {
	g.ALL = field.NewAsterisk(table)
	g.VideoGameTitles = field.NewField(table, "video_game_titles")
	g.Generation = field.NewInt64(table, "generation")

	g.fillFieldMap()

	return g
}

func (g *generation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *generation) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 2)
	g.fieldMap["video_game_titles"] = g.VideoGameTitles
	g.fieldMap["generation"] = g.Generation
}

func (g generation) clone(db *gorm.DB) generation {
	g.generationDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g generation) replaceDB(db *gorm.DB) generation {
	g.generationDo.ReplaceDB(db)
	return g
}

type generationDo struct{ gen.DO }

func (g generationDo) Debug() *generationDo {
	return g.withDO(g.DO.Debug())
}

func (g generationDo) WithContext(ctx context.Context) *generationDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g generationDo) ReadDB() *generationDo {
	return g.Clauses(dbresolver.Read)
}

func (g generationDo) WriteDB() *generationDo {
	return g.Clauses(dbresolver.Write)
}

func (g generationDo) Session(config *gorm.Session) *generationDo {
	return g.withDO(g.DO.Session(config))
}

func (g generationDo) Clauses(conds ...clause.Expression) *generationDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g generationDo) Returning(value interface{}, columns ...string) *generationDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g generationDo) Not(conds ...gen.Condition) *generationDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g generationDo) Or(conds ...gen.Condition) *generationDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g generationDo) Select(conds ...field.Expr) *generationDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g generationDo) Where(conds ...gen.Condition) *generationDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g generationDo) Order(conds ...field.Expr) *generationDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g generationDo) Distinct(cols ...field.Expr) *generationDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g generationDo) Omit(cols ...field.Expr) *generationDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g generationDo) Join(table schema.Tabler, on ...field.Expr) *generationDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g generationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *generationDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g generationDo) RightJoin(table schema.Tabler, on ...field.Expr) *generationDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g generationDo) Group(cols ...field.Expr) *generationDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g generationDo) Having(conds ...gen.Condition) *generationDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g generationDo) Limit(limit int) *generationDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g generationDo) Offset(offset int) *generationDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g generationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *generationDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g generationDo) Unscoped() *generationDo {
	return g.withDO(g.DO.Unscoped())
}

func (g generationDo) Create(values ...*model.Generation) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g generationDo) CreateInBatches(values []*model.Generation, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g generationDo) Save(values ...*model.Generation) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g generationDo) First() (*model.Generation, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Generation), nil
	}
}

func (g generationDo) Take() (*model.Generation, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Generation), nil
	}
}

func (g generationDo) Last() (*model.Generation, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Generation), nil
	}
}

func (g generationDo) Find() ([]*model.Generation, error) {
	result, err := g.DO.Find()
	return result.([]*model.Generation), err
}

func (g generationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Generation, err error) {
	buf := make([]*model.Generation, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g generationDo) FindInBatches(result *[]*model.Generation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g generationDo) Attrs(attrs ...field.AssignExpr) *generationDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g generationDo) Assign(attrs ...field.AssignExpr) *generationDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g generationDo) Joins(fields ...field.RelationField) *generationDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g generationDo) Preload(fields ...field.RelationField) *generationDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g generationDo) FirstOrInit() (*model.Generation, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Generation), nil
	}
}

func (g generationDo) FirstOrCreate() (*model.Generation, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Generation), nil
	}
}

func (g generationDo) FindByPage(offset int, limit int) (result []*model.Generation, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g generationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g generationDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g generationDo) Delete(models ...*model.Generation) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *generationDo) withDO(do gen.Dao) *generationDo {
	g.DO = *do.(*gen.DO)
	return g
}
